# Travis CI configuration for psycopg3

language: python

env:
  global:
    - PSYCOPG3_TEST_DSN=dbname=psycopg3_test

matrix:
  include:

    - env:
        - TOXENV=black
        - TOXDIR=.
      python: 3.8

    - env:
        - TOXENV=flake8
        - TOXDIR=.
      python: 3.8

    - env:
        - TOXENV=mypy
        - TOXDIR=.
      python: 3.8

    - python: 3.6
      addons:
        postgresql: '10'
        apt:
          packages:
            - postgresql-client-10
      env:
        - TOXENV=py36
        - TOXDIR=psycopg3_c
        - PGVER=10
        - PSYCOPG3_IMPL=c
        - PGPORT=5432
          # skip tests failing on importing psycopg3_c.pq on subprocess
          # they only fail on Travis, work ok locally under tox too.
        - PYTEST_ADDOPTS="-m 'not subprocess'"

    - python: 3.6
      addons:
        postgresql: '11'
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
      env:
        - TOXENV=py36
        - TOXDIR=psycopg3
        - PGVER=11
        - PSYCOPG3_IMPL=python
        - PGPORT=5433

    - python: 3.7
      addons:
        postgresql: '11'
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
      env:
        - TOXENV=py37
        - TOXDIR=psycopg3_c
        - PGVER=11
        - PSYCOPG3_IMPL=c
        - PGPORT=5433
        - PYTEST_ADDOPTS="-m 'not subprocess'"

    - python: 3.7
      addons:
        postgresql: '12'
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      env:
        - TOXENV=py37
        - TOXDIR=psycopg3
        - PGVER=11
        - PSYCOPG3_IMPL=python
        - PGPORT=5433

    - python: 3.8
      addons:
        postgresql: '12'
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      env:
        - TOXENV=py38
        - TOXDIR=psycopg3_c
        - PGVER=12
        - PSYCOPG3_IMPL=c
        - PGPORT=5433
        - PYTEST_ADDOPTS="-m 'not subprocess'"

    - python: 3.8
      addons:
        postgresql: '12'
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      env:
        - TOXENV=py38
        - TOXDIR=psycopg3
        - PGVER=12
        - PSYCOPG3_IMPL=python
        - PGPORT=5433
        - BUILD_DOCS=1

install:
  - pip install tox
  - test ${TOXENV:0:2} != py || psql -c 'create database psycopg3_test'

script:
  - tox -c $TOXDIR

deploy:
  - provider: script
    script: bash tools/travis_update_docs.sh
    on:
      branch: master
      condition: "$BUILD_DOCS = 1"
