# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'fix_db_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

from typing import Any

import pytest

from psycopg import Connection
from psycopg import errors as e
from psycopg import pq
from psycopg.replication import (
    LogicalReplicationConnection,
    LogicalReplicationCursor,
    PhysicalReplicationConnection,
)
from psycopg.replication.logical_output_plugins.decoder import DispatchingDecoder

from .utils import get_restart_lsn
from ..fix_db import maybe_trace


@pytest.fixture
def application_name():
    return "psycopg_testing"


@pytest.fixture
def conn(conn):
    conn.set_autocommit(True)
    yield conn


@pytest.fixture
def logical_conn(dsn, slot_name, application_name, tracefile, request):
    # NOTE: slot_name is a dependency so conn is closed before slot is cleaned up
    conn = LogicalReplicationConnection.connect(
        dsn, autocommit=True, application_name=application_name
    )
    with conn.cursor() as cur:
        cur.execute("SHOW wal_level")
        assert (row := cur.fetchone()) is not None
        wal_level = row[0]
    if wal_level != "logical":
        conn.close()
        pytest.skip(
            "wal_level must be 'logical' to use logical replication,"
            + f" got '{wal_level}'"
        )
    with maybe_trace(conn.pgconn, tracefile, request.function):
        yield conn
    conn.close()


@pytest.fixture
def client_encoding():
    return None


@pytest.fixture
def physical_conn(
    dsn, slot_name, application_name, client_encoding, request, tracefile
):
    # NOTE: slot_name is a dependency so conn is closed before slot is cleaned up
    extra_connect_kwargs = {}
    if client_encoding is not None:
        extra_connect_kwargs["client_encoding"] = client_encoding
    conn = PhysicalReplicationConnection.connect(
        dsn, autocommit=True, application_name=application_name, **extra_connect_kwargs
    )
    with maybe_trace(conn.pgconn, tracefile, request.function):
        yield conn
    conn.close()


@pytest.fixture()
def set_origin(conn, origin):
    conn.execute("SELECT pg_replication_origin_session_setup(%s)", [origin])
    try:
        yield origin
    finally:
        try:
            conn.execute("SELECT pg_replication_origin_session_reset()")
        except e.ObjectNotInPrerequisiteState:
            pass


@pytest.fixture
def row_factory():
    return None


@pytest.fixture
def format():
    return pq.Format.TEXT


@pytest.fixture
def streaming():
    return None


@pytest.fixture
def two_phase():
    return None


@pytest.fixture
def physical_started_cur(physical_conn, conn, slot_name):
    with physical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name, temporary=True, reserve_wal=True)
        restart_lsn = get_restart_lsn(conn, slot_name, cur)
        cur.start_replication(slot_name, start_lsn=restart_lsn)
        yield cur


@pytest.fixture
def decoder(row_factory):
    decoder_kwargs = {}
    if row_factory is not None:
        decoder_kwargs["row_factory"] = row_factory

    return DispatchingDecoder(**decoder_kwargs)


@pytest.fixture
def logical_started_cur(
    logical_conn, slot_name, publication, format, streaming, two_phase, decoder
):
    start_replication_kwargs: dict[str, Any] = {}

    if format is pq.Format.BINARY:
        start_replication_kwargs["binary"] = True
    if streaming is not None:
        start_replication_kwargs["streaming"] = streaming
        if streaming == "parallel":
            start_replication_kwargs["proto_version"] = 4
    if two_phase is not None:
        start_replication_kwargs["two_phase"] = two_phase
        proto_version = start_replication_kwargs.get("proto_version", 2)
        start_replication_kwargs["proto_version"] = max(proto_version, 3)

    with logical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name, temporary=True)

        if streaming is not None and streaming != "off":
            # determines when transactions start to be streamed
            cur.execute("SET logical_decoding_work_mem = '64kB'")
        cur.start_replication(
            slot_name,
            publication_names=publication,
            messages=True,
            decoder=decoder,
            **start_replication_kwargs,
        )
        yield cur


@pytest.fixture
def repl_conn_cls():
    return LogicalReplicationConnection


@pytest.fixture
def repl_cur_cls():
    return LogicalReplicationCursor


@pytest.fixture
def repl_cur(dsn, repl_conn_cls, repl_cur_cls, slot_name, tracefile, request):
    # NOTE: slot_name is a dependency so conn is closed before slot is cleaned up
    extra_connect_kwargs = {}
    if repl_conn_cls is Connection:
        extra_connect_kwargs["replication"] = "database"
    conn = repl_conn_cls.connect(
        dsn, autocommit=True, cursor_factory=repl_cur_cls, **extra_connect_kwargs
    )
    with conn.cursor() as cur:
        with maybe_trace(conn.pgconn, tracefile, request.function):
            yield cur
    conn.close()


LOGICAL_STARTED_CUR = "logical_started_cur"
PHYSICAL_STARTED_CUR = "physical_started_cur"


@pytest.fixture(
    params=[
        pytest.param(LOGICAL_STARTED_CUR, id="logical"),
        pytest.param(PHYSICAL_STARTED_CUR, id="physical"),
    ]
)
def repl_started_cur(request, decoder, slot_name):
    # NOTE: decoder is used by logical_started_cur
    # NOTE: slot_name is a dependency so conn is closed before slot is cleaned up
    cur = request.getfixturevalue(request.param)
    yield cur
