# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'test_replication_connection_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

import pytest

from psycopg.replication import (
    LogicalReplicationConnection,
    LogicalReplicationCursor,
    PhysicalReplicationConnection,
    PhysicalReplicationCursor,
)

from .params import repl_class_param


@pytest.mark.parametrize(
    "conn_cls,replication_val",
    [
        repl_class_param(PhysicalReplicationConnection, b"true"),
        repl_class_param(LogicalReplicationConnection, b"database"),
    ],
)
def test_connect(dsn, conn_cls, replication_val):
    with conn_cls.connect(dsn, autocommit=True) as conn:
        assert not conn.closed
        assert (
            replication_val
            == next(
                (
                    conn_option
                    for conn_option in conn.pgconn.info
                    if conn_option.keyword == b"replication"
                )
            ).val
        )
    assert conn.closed


@pytest.mark.parametrize(
    "conn_cls",
    [
        repl_class_param(PhysicalReplicationConnection),
        repl_class_param(LogicalReplicationConnection),
    ],
)
def test_connect_replication_param_rejected(dsn, conn_cls):
    """Passing 'replication' explicitly should raise ValueError."""
    for val in ("true", "database"):
        with pytest.raises(ValueError, match="replication"):
            conn_cls.connect(dsn, autocommit=True, replication=val)
        with pytest.raises(ValueError, match="replication"):
            conn_cls.connect(dsn + f" replication={val}")


@pytest.mark.parametrize(
    "conn_cls,cur_cls",
    [
        repl_class_param(PhysicalReplicationConnection, PhysicalReplicationCursor),
        repl_class_param(LogicalReplicationConnection, LogicalReplicationCursor),
    ],
)
def test_default_cursor_factory(dsn, conn_cls, cur_cls):
    with conn_cls.connect(dsn) as conn:
        assert conn.cursor_factory is cur_cls
        with conn.cursor() as cur:
            assert isinstance(cur, cur_cls)
