# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'test_logical_replication_cursor_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

import pytest

from psycopg import errors as e
from psycopg import sql
from psycopg.replication.replication_options import SnapshotOption


def check_logical_stream_health(conn, started_cur, table, timeout=0.5):
    started_cur.send_feedback(request_reply=True)

    started_cur.read_message(timeout=timeout)

    conn.execute("SELECT pg_logical_emit_message(false, 'test_psycopg', 'SUBSCRIBED')")

    started_cur.read_message(return_keepalive_messages=False, timeout=timeout)

    while True:
        try:
            started_cur.read_message(return_keepalive_messages=False, timeout=0.1)
        except e.ReadMessageTimeout:
            break

    conn.execute(f"INSERT INTO {table} (data) VALUES ('healthy?')")

    return started_cur.read_message(return_keepalive_messages=False, timeout=timeout)


def test_start_replication(conn, logical_conn, slot_name, test_table, publication):
    with logical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name)
        cur.start_replication(
            slot_name, publication_names=publication, decoder=None, messages=True
        )
        check_logical_stream_health(conn, cur, test_table)


def test_start_replication_multiple_publications(
    conn,
    logical_conn,
    slot_name,
    test_table,
    publication,
    empty_publication,
    monkeypatch,
):
    with logical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name)
        orig_execute = cur.execute
        statement: str

        def mock_execute(*args, **kwargs):
            nonlocal statement
            statement = sql.as_string(args[0])
            return orig_execute(*args, **kwargs)

        with monkeypatch.context() as m:
            m.setattr(cur, "execute", mock_execute)
            cur.start_replication(
                slot_name,
                publication_names=[empty_publication, publication],
                decoder=None,
                messages=True,
            )
        assert (
            f""""publication_names" '"{empty_publication}", "{publication}"'"""
            in statement
        )
        check_logical_stream_health(conn, cur, test_table)


def test_start_replication_string_lsn(
    conn, logical_conn, slot_name, test_table, publication
):
    """start_replication should accept a string LSN."""
    with logical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name)
        cur.start_replication(
            slot_name,
            start_lsn="0/0",
            publication_names=publication,
            decoder=None,
            messages=True,
        )
        check_logical_stream_health(conn, cur, test_table)


@pytest.mark.parametrize("option_value", [True, False])
@pytest.mark.parametrize(
    "option_name",
    [
        "include_xids",
        "include_timestamp",
        "force_binary",
        "skip_empty_xacts",
        "only_local",
        "include_rewrites",
        "stream_changes",
    ],
)
def test_start_replication_text_decoder(
    conn, logical_conn, slot_name, test_table, publication, option_name, option_value
):
    with logical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name, output_plugin="test_decoding")
        cur.start_replication(slot_name, start_lsn="0/0", **{option_name: option_value})
        begin = check_logical_stream_health(conn, cur, test_table)
        insert = cur.read_message(timeout=1, return_keepalive_messages=False)
        commit = cur.read_message(timeout=1, return_keepalive_messages=False)

        for msg in (begin, insert, commit):
            assert isinstance(msg.payload, str)

        assert "INSERT" in insert.payload
        assert test_table in insert.payload
        assert "'healthy?'" in insert.payload

        if option_name == "include_xids" and option_value is False:
            assert "BEGIN" == begin.payload
            assert "COMMIT" == commit.payload
        else:
            assert "BEGIN " in begin.payload
            assert "COMMIT " in commit.payload


@pytest.mark.pg(">=15")
def test_create_slot_snapshot_use(logical_conn, slot_name):
    with logical_conn.transaction():
        with pytest.raises(e.InternalError_):
            with logical_conn.cursor() as cur:
                *_, snapshot_name, _ = cur.create_replication_slot(
                    slot_name, snapshot=SnapshotOption.USE
                )
    with logical_conn.transaction():
        # READ ONLY required on PostgreSQL 16+
        logical_conn.execute(
            "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY"
        )
        with logical_conn.cursor() as cur:
            *_, snapshot_name, _ = cur.create_replication_slot(
                slot_name, snapshot=SnapshotOption.USE
            )
    assert snapshot_name is None


@pytest.mark.pg(">=15")
def test_create_slot_snapshot_export(conn, logical_conn, slot_name):
    with logical_conn.cursor() as cur:
        *_, snapshot_name, _ = cur.create_replication_slot(
            slot_name, snapshot=SnapshotOption.EXPORT
        )
    assert snapshot_name is not None
    with conn.transaction():
        conn.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ")
        conn.execute(f"SET TRANSACTION SNAPSHOT '{snapshot_name}'")


@pytest.mark.pg(">=15")
def test_create_slot_snapshot_nothing(logical_conn, slot_name):
    with logical_conn.cursor() as cur:
        *_, snapshot_name, _ = cur.create_replication_slot(
            slot_name, snapshot=SnapshotOption.NOTHING
        )
    assert snapshot_name is None


@pytest.mark.pg(">=17")
@pytest.mark.parametrize(
    "replication_slot_opts",
    [
        pytest.param(("failover",), id="failover", marks=[pytest.mark.pg("==17")]),
        pytest.param(
            ("failover", "two_phase"),
            id="two_phase-failover",
            marks=[pytest.mark.pg(">=18")],
        ),
    ],
)
def test_alter_replication_slot(logical_conn, slot_name, replication_slot_opts):

    def get_options(cur):
        cur.execute(
            f"SELECT {', '.join(replication_slot_opts)}"
            + " FROM pg_replication_slots WHERE slot_name = %s",
            [slot_name],
        )
        return cur.fetchone()

    with logical_conn.cursor() as cur:
        cur.create_replication_slot(
            slot_name, **{opt: False for opt in replication_slot_opts}
        )
        for option in get_options(cur):
            assert option is False
        cur.alter_replication_slot(
            slot_name, **{opt: True for opt in replication_slot_opts}
        )
        for option in get_options(cur):
            assert option is True


@pytest.mark.pg("<17")
def test_alter_replication_slot_raises(logical_conn, slot_name):
    with logical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name, two_phase=False)
        with pytest.raises(ValueError, match="alter_replication_slot()"):
            cur.alter_replication_slot(slot_name, two_phase=True)
