# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'test_physical_replication_cursor_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

from contextlib import contextmanager

import pytest

import psycopg
from psycopg.replication.replication_messages import (
    PrimaryKeepaliveMessage,
    XLogDataMessage,
)

from .utils import get_last_flushed_lsn, get_restart_lsn


@contextmanager
def generate_traffic(conn, n=1):
    with conn.cursor() as cur:
        cur.execute(
            "CREATE TABLE IF NOT EXISTS traffic (id BIGSERIAL PRIMARY KEY, data TEXT);"
        )
        cur.execute(
            "INSERT INTO traffic (data)"
            + " SELECT md5(random()::text)"
            + f" FROM generate_series(1, {n}) AS s(i);"
        )

        try:
            yield
        finally:
            cur.execute("DROP TABLE traffic;")


def test_start_replication_slotless(conn, physical_conn):
    with physical_conn.cursor() as cur:
        cur.start_replication(start_lsn=get_last_flushed_lsn(cur))
        with generate_traffic(conn):
            msg = cur.read_message()
    assert isinstance(msg, (XLogDataMessage, PrimaryKeepaliveMessage))


# DISCUSS: should we set client_encoding by default in PhysicalReplicationConnection?
# The bytes behaviour of SQL-ASCII is probably unexpected for users of psycopg


@pytest.mark.parametrize("client_encoding", ["utf-8"])
def test_start_replication_with_slot(conn, physical_conn, slot_name):
    with physical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name, reserve_wal=True)
        restart_lsn = get_restart_lsn(conn, slot_name, cur)

        cur.start_replication(slot_name=slot_name, start_lsn=restart_lsn)
        with generate_traffic(conn):
            msg = cur.read_message()
    assert isinstance(msg, (XLogDataMessage, PrimaryKeepaliveMessage))


def test_start_replication_missing_wal_raises(physical_conn):
    with physical_conn.cursor() as cur:
        cur.start_replication(start_lsn="0/0")
        with pytest.raises(psycopg.errors.UndefinedFile):
            cur.read_message()


@pytest.mark.pg(">=15")
def test_read_replication_slot_dne(physical_conn, slot_name):
    with physical_conn.cursor() as cur:
        slot_type, restart_lsn, restart_tli = cur.read_replication_slot(slot_name)

    assert slot_type is None
    assert restart_lsn is None
    assert restart_tli is None


@pytest.mark.pg(">=15")
def test_read_replication_slot(physical_conn, slot_name):
    with physical_conn.cursor() as cur:
        cur.create_replication_slot(slot_name)

        slot_type, restart_lsn, restart_tli = cur.read_replication_slot(slot_name)

    assert slot_type == b"physical"
    # haven't passed reserve_wal
    assert restart_lsn is None
    assert restart_tli is None


@pytest.mark.pg("<15")
def test_read_replication_slot_raises(physical_conn, slot_name):
    with physical_conn.cursor() as cur:
        with pytest.raises(ValueError, match="read_replication_slot()"):
            cur.read_replication_slot(slot_name)
