# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'utils_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

from typing import Any
from contextlib import contextmanager

import pytest

import psycopg
from psycopg import errors as e
from psycopg.rows import scalar_row
from psycopg.replication.replication_messages import XLogDataMessage
from psycopg.replication.logical_output_plugins.pgoutput.pgoutput_messages import (
    PgOutputMessage,
)

from ..acompat import gather, spawn


def collect_xlogdata_messages(
    cur: Any, until: type[PgOutputMessage] | None = None, n: int = 400, **kwargs: Any
) -> list[XLogDataMessage[Any]]:
    """
    Consume the replication stream until n XLogData messages have been
    collected or message payload is of type `until`
    Returns the list of XLogDataMessage objects.
    """
    kwargs["return_keepalive_messages"] = False
    messages: list[XLogDataMessage[Any]] = []
    while len(messages) < n:
        msg = cur.read_message(**kwargs, timeout=2)
        messages.append(msg)
        if until is not None and isinstance(msg.payload, until):
            break
    return messages


def replica_identity_full(conn, table, logical_cur):
    conn.execute(f"ALTER TABLE {table} REPLICA IDENTITY FULL")
    if conn.info.server_version < 150000:
        # consume empty begin/commit pairs generated on old versions
        collect_xlogdata_messages(logical_cur, n=2)


def replica_identity_default(conn, table, logical_cur):
    pass


def replica_identity_index(conn, table, logical_cur):
    index_name = f"data_uniq_{table}"
    with conn.transaction():
        conn.execute(f"CREATE UNIQUE INDEX {index_name} ON {table} (data)")
        conn.execute(f"ALTER TABLE {table} REPLICA IDENTITY USING index {index_name}")
    if conn.info.server_version < 150000:
        # consume empty begin/commit pairs generated on old versions
        collect_xlogdata_messages(logical_cur, n=2)


def insert_data(conn, table, value, return_xid=False, returning=None):
    with conn.cursor() as cur:
        statement = f"INSERT INTO {table} (data) VALUES (%s)"
        if return_xid:
            with conn.transaction():
                cur.execute(statement, [value])
                cur.execute("SELECT pg_current_xact_id()")
                (xid,) = cur.fetchone()
                return int(xid)
        else:
            if returning:
                statement += f" RETURNING {returning}"
            cur.execute(statement, [value])
            if returning:
                return cur.fetchone()[0]


def execute_streaming_insert(has_execute, table, extra_data=None, n=320):
    columns = "data"
    extra_vals = ""
    if extra_data is not None:
        columns = f"{columns}, {', '.join(extra_data.keys())}"
        extra_vals = ", " + ", ".join(extra_data.values())

    has_execute.execute(
        f"INSERT INTO {table} ({columns})"
        + " SELECT i ||"
        + " ': this is a pretty long string for testing streaming transactions"
        + f" :' || i{extra_vals}"
        + f" FROM generate_series(1,{n}) AS t(i);"
    )


def get_xid(cur):
    cur.execute("SELECT pg_current_xact_id()")
    (xid,) = cur.fetchone()

    return int(xid)


@contextmanager
def start_streaming_insert(
    conn, table, exec_first=None, extra_data=None, n=320, rollback=False
):
    with conn.cursor() as cur:
        with conn.transaction():
            if exec_first is not None:
                exec_first()
            execute_streaming_insert(conn, table, extra_data=extra_data, n=n)

            yield get_xid(cur)

            if rollback:
                raise psycopg.Rollback()


def streaming_insert(conn, table, exec_first=None):
    with start_streaming_insert(conn, table, exec_first) as xid:
        return xid


@contextmanager
def two_phase_insert(conn, xname, table, streaming, rollback=False):
    conn.set_autocommit(False)

    # DISCUSS: test hangs if `xname`` already exists; shouldn't psycopg handle this?
    conn.tpc_begin(xname)
    with conn.cursor() as cur:
        xid = get_xid(cur)
    if streaming == "on":
        execute_streaming_insert(conn, table)
    else:
        insert_data(conn, table, "two phase")

    try:
        conn.tpc_prepare()
    except e.NotSupportedError as err:
        pytest.skip(str(err))

    try:
        yield xid
    finally:
        if rollback:
            conn.tpc_rollback()
        else:
            conn.tpc_commit()


@contextmanager
def generate_table_traffic(has_execute, table, n=100):
    tasks = []
    for _ in range(n // 10):
        tasks.append(
            spawn(
                has_execute.execute,
                [
                    f"INSERT INTO {table} (data) SELECT md5(random()::text)"
                    + "FROM generate_series(1, 10)"
                ],
            )
        )
    try:
        yield
    finally:
        gather(*tasks)


def get_last_flushed_lsn(physical_cur):
    _, _, lsn, _ = physical_cur.identify_system()
    if isinstance(lsn, bytes):
        lsn = lsn.decode("ascii")
    return lsn


def get_replication_info(conn, application_name, fields):
    if isinstance(fields, str):
        fields = [fields]
    fields_str = ", ".join(
        (f"{f} - '0/0'" if f.endswith("_lsn") else f for f in fields)
    )
    with conn.cursor(binary=True) as cur:
        # cur.adapters.register_loader(
        #     "timestamptz", psycopg.types.numeric.Int8BinaryLoader
        # )
        cur.execute(
            f"SELECT {fields_str} FROM"
            + " pg_stat_replication WHERE application_name=%s",
            [application_name],
        )
        result = cur.fetchone()
        if len(fields) == 1:
            result = result[0]
        return result


def get_restart_lsn(conn, slot_name, physical_cur=None):
    if physical_cur is None or conn.info.server_version < 150000:
        with conn.cursor(row_factory=scalar_row) as cur:
            cur.execute(
                "SELECT restart_lsn from pg_replication_slots WHERE slot_name = %s",
                [slot_name],
            )
            restart_lsn = cur.fetchone()
    else:
        _, restart_lsn, _ = physical_cur.read_replication_slot(slot_name)
        if isinstance(restart_lsn, bytes):
            restart_lsn = restart_lsn.decode("ascii")
    return restart_lsn
