cdef object load_int_text(const char *data, size_t length, void *context)
cdef object load_int2_binary(const char *data, size_t length, void *context)
cdef object load_int4_binary(const char *data, size_t length, void *context)
cdef object load_int8_binary(const char *data, size_t length, void *context)
cdef object load_oid_binary(const char *data, size_t length, void *context)
cdef object load_bool_binary(const char *data, size_t length, void *context)
