# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'logical_replication_cursor_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

import time
import logging
from typing import LiteralString

from .. import sql
from ..rows import Row
from .._compat import Self
from .replication_utils import lsn_to_string, string_to_lsn
from .replication_options import ReplicationType
from .base_replication_cursor import BaseReplicationCursor

logger = logging.getLogger("psycopg")


class LogicalReplicationCursor(BaseReplicationCursor[Row]):
    __module__ = "psycopg.replication"

    replication_type = ReplicationType.LOGICAL

    def start_replication(self, slot_name: str, start_lsn: int | str = 0) -> Self:
        if isinstance(start_lsn, str):
            # NOTE: this validates the string format in a simple manner at the
            # expense of an unnecessary conversion.
            start_lsn = string_to_lsn(start_lsn)

        statement = sql.SQL(
            "START_REPLICATION SLOT {slot_name} LOGICAL {start_lsn}"
        ).format(
            slot_name=sql.BareIdentifier(slot_name),
            start_lsn=sql.SQL(lsn_to_string(start_lsn)),
        )

        self.execute(statement)
        self._last_feedback_time = time.monotonic()
        self._last_received_lsn = start_lsn
        self.last_flushed_lsn = start_lsn
        self.last_applied_lsn = start_lsn

        return self

    def alter_replication_slot(
        self,
        slot_name: str,
        two_phase: bool | None = None,
        failover: bool | None = None,
    ) -> Self:
        if self._conn.info.server_version < 170000:
            raise ValueError(
                "'alter_replication_slot()' is not supported on this version of"
                + " PostgreSQL"
            )
        options: dict[LiteralString, str] = {}
        if two_phase is not None:
            options["TWO_PHASE"] = str(bool(two_phase)).lower()
        if failover is not None:
            options["FAILOVER"] = str(bool(failover)).lower()

        statement = sql.SQL("ALTER_REPLICATION_SLOT {slot_name}").format(
            slot_name=sql.BareIdentifier(slot_name)
        )
        if options:
            statement += sql.SQL(" ({options})").format(
                options=self._format_sql_options(options)
            )

        return self.execute(statement)
