# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'logical_replication_cursor_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

import time
import logging
from typing import Any, Callable, cast
from weakref import ReferenceType, ref
from functools import partial

from .. import adapt, sql
from ..abc import Loader
from ..rows import Row, tuple_row
from .._compat import LiteralString, Self
from .replication_utils import lsn_to_string, string_to_lsn
from .replication_options import ReplicationType
from .replication_messages import DecodedPayload
from .logical_output_plugins import DispatchingDecoder, get_output_plugin_options
from .base_replication_cursor import BaseReplicationCursor
from .logical_output_plugins.abc import LogicalXLogDataDecoder

logger = logging.getLogger("psycopg")


class LogicalReplicationCursor(BaseReplicationCursor[Row]):
    __module__ = "psycopg.replication"

    replication_type = ReplicationType.LOGICAL
    decode_xlogdata: LogicalXLogDataDecoder[Any] | None

    def _format_output_plugin_options(
        self, output_plugin_options: dict[str, str]
    ) -> sql.Composed:
        return sql.SQL(", ").join(
            (
                sql.SQL("{opt_name} {opt}").format(
                    opt_name=sql.Identifier(opt_name), opt=str(opt)
                )
                for opt_name, opt in output_plugin_options.items()
            )
        )

    def output_plugin_for_slot(self, slot_name: str) -> str:
        with self._conn.cursor(row_factory=tuple_row) as cursor:
            cursor.execute(
                "SELECT plugin FROM pg_replication_slots "
                + "WHERE slot_type = 'logical' AND slot_name = %s;",
                [slot_name],
            )
            result = cursor.fetchall()
        if not result:
            raise ValueError(f"No logical replication slot named {slot_name}")
        output_plugin = cast(str, result[0][0])

        return output_plugin

    def start_replication(
        self,
        slot_name: str,
        start_lsn: int | str = 0,
        decoder: LogicalXLogDataDecoder[DecodedPayload] | None = DispatchingDecoder(),
        raw_output_plugin_options: dict[str, str] | None = None,
        **output_plugin_options: Any,
    ) -> Self:
        if raw_output_plugin_options and output_plugin_options:
            raise TypeError(
                "Only one of 'raw_output_plugin_options' and 'output_plugin_options'"
                + " can be passed to start_replication()"
            )

        if isinstance(start_lsn, str):
            # NOTE: this validates the string format in a simple manner at the
            # expense of an unnecessary conversion.
            start_lsn = string_to_lsn(start_lsn)

        if output_plugin_options or (
            decoder is not None and decoder.output_plugin is None
        ):
            self._output_plugin = self.output_plugin_for_slot(slot_name)

        if output_plugin_options:
            plugin_opts = get_output_plugin_options(self._output_plugin)(
                output_plugin_options
            )
            plugin_opts.validate_opts()
            output_plugin_options = plugin_opts.string_opts
        else:
            output_plugin_options = raw_output_plugin_options or {}

        if decoder is not None:
            decoder.plugin_options = plugin_opts.opts if output_plugin_options else {}
            if decoder.output_plugin is None:
                decoder.output_plugin = self._output_plugin
            decoder.server_encoding = self._encoding
            decoder._tx = adapt.Transformer(self)
            # Set up a callback to allow changing loaders
            # since decoder shares an adapt context with the cursor
            _orig_callback = self._adapters._register_loader_callback
            self._adapters._register_loader_callback = partial(
                self._loaders_changed_replication, ref(self), _orig_callback
            )
            decoder = decoder.get_real_decoder()
        self.decode_xlogdata = decoder

        statement = sql.SQL(
            "START_REPLICATION SLOT {slot_name} LOGICAL {start_lsn}"
        ).format(
            slot_name=sql.BareIdentifier(slot_name),
            start_lsn=sql.SQL(lsn_to_string(start_lsn)),
        )

        if output_plugin_options:
            statement += sql.SQL(" ({options})").format(
                options=self._format_output_plugin_options(output_plugin_options)
            )
        self.execute(statement)
        self._started_replication_slot = slot_name
        self._last_feedback_time = time.monotonic()
        self._last_received_lsn = start_lsn
        self.last_flushed_lsn = start_lsn
        self.last_applied_lsn = start_lsn

        return self

    @classmethod
    def _loaders_changed_replication(
        cls,
        wself: ReferenceType[LogicalReplicationCursor[Any]],
        orig_callback: Callable[[int, type[Loader]], None] | None,
        oid: int,
        loader: type[Loader],
    ) -> None:
        if not (self := wself()):
            return

        if orig_callback is not None:
            orig_callback(oid, loader)

        if self.decode_xlogdata is None:
            return

        self.decode_xlogdata._tx = adapt.Transformer(self)

    def alter_replication_slot(
        self,
        slot_name: str,
        two_phase: bool | None = None,
        failover: bool | None = None,
    ) -> Self:
        if self._conn.info.server_version < 170000:
            raise ValueError(
                "'alter_replication_slot()' is not supported on this version of"
                + " PostgreSQL"
            )
        options: dict[LiteralString, str] = {}
        if two_phase is not None:
            options["TWO_PHASE"] = str(bool(two_phase)).lower()
        if failover is not None:
            options["FAILOVER"] = str(bool(failover)).lower()

        statement = sql.SQL("ALTER_REPLICATION_SLOT {slot_name}").format(
            slot_name=sql.BareIdentifier(slot_name)
        )
        if options:
            statement += sql.SQL(" ({options})").format(
                options=self._format_sql_options(options)
            )

        return self.execute(statement)
