# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'physical_replication_cursor_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

import time
import logging
from typing import cast

from .. import sql
from .abc import XLogDataDecoder
from ..rows import Row
from .._compat import Self
from .replication_utils import lsn_to_string, string_to_lsn
from .replication_options import ReplicationType
from .replication_messages import DecodedPayload
from .base_replication_cursor import BaseReplicationCursor

logger = logging.getLogger("psycopg")


class PhysicalReplicationCursor(BaseReplicationCursor[Row]):
    __module__ = "psycopg.replication"

    replication_type = ReplicationType.PHYSICAL

    def start_replication(
        self,
        slot_name: str | None = None,
        start_lsn: int | str | None = None,
        timeline: int | None = None,
        decoder: XLogDataDecoder[DecodedPayload] | None = None,
    ) -> Self:
        """
        Start physical replication.
        """
        if start_lsn is None:
            # TASK: When PostgreSQL 14 goes out of support,
            # we can default this to using the restart_lsn from
            # read_replication_slot.
            raise TypeError(
                f"{type(self).__name__}.start_replication() missing 1 required"
                + " argument: 'start_lsn'"
            )
        elif isinstance(start_lsn, str):
            start_lsn = string_to_lsn(start_lsn)

        self.decode_xlogdata = decoder
        if decoder is not None:
            decoder.server_encoding = self._encoding

        if slot_name is not None:
            statement = sql.SQL(
                "START_REPLICATION SLOT {slot_name} PHYSICAL {start_lsn}"
            ).format(
                slot_name=sql.BareIdentifier(slot_name),
                start_lsn=sql.SQL(lsn_to_string(start_lsn)),
            )
        else:
            statement = sql.SQL("START_REPLICATION PHYSICAL {start_lsn}").format(
                start_lsn=sql.SQL(lsn_to_string(start_lsn))
            )

        if timeline is not None:
            statement += statement + sql.SQL(" TIMELINE {timeline}").format(
                timeline=sql.BareIdentifier(str(timeline))
            )

        self.execute(statement)
        self._last_received_lsn = start_lsn
        self.last_flushed_lsn = start_lsn
        self.last_applied_lsn = start_lsn
        self._last_feedback_time = time.monotonic()

        return self

    def read_replication_slot(self, slot_name: str) -> Row:
        """
        Read information about a replication slot.

        Executes the `READ_REPLICATION_SLOT slot_name` command and returns
        a row containing the slot type, restart lsn, and
        restart timeline. If the slot does not exist, all values will be `None`.

        See https://www.postgresql.org/docs/current/protocol-replication.html#PROTOCOL-REPLICATION-READ-REPLICATION-SLOT
        """  # noqa: E501
        if self._conn.info.server_version < 150000:
            raise ValueError(
                "'read_replication_slot()' is not supported on this version of"
                + " PostgreSQL"
            )
        self.execute(
            sql.SQL("READ_REPLICATION_SLOT {slot_name}").format(
                slot_name=sql.BareIdentifier(slot_name)
            )
        )

        return cast(Row, self.fetchone())
