# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'replication_connection_async.py'
# DO NOT CHANGE! Change the original file instead.
from __future__ import annotations

import logging
from typing import TYPE_CHECKING, cast

from ..abc import AdaptContext, ConnParam
from ..rows import Row, RowFactory, tuple_row
from ..cursor import Cursor
from .._compat import Self
from ..connection import Connection
from ..client_cursor import ClientCursor
from .._server_cursor import ServerCursor
from .logical_replication_cursor import LogicalReplicationCursor
from .physical_replication_cursor import PhysicalReplicationCursor

if TYPE_CHECKING:
    from ..pq.abc import PGconn

logger = logging.getLogger("psycopg")


class BaseReplicationConnection(Connection[Row]):
    __module__ = "psycopg.replication"

    # Only simple query protocol is supported in ReplicationConnections
    # so use ClientCursors only
    cursor_factory: type[ClientCursor[Row]]
    server_cursor_factory: type[ServerCursor[Row]]
    row_factory: RowFactory[Row]

    _replication_connection_string: str

    @classmethod
    def connect(
        cls,
        conninfo: str = "",
        *,
        autocommit: bool = False,
        prepare_threshold: int | None = 5,
        context: AdaptContext | None = None,
        row_factory: RowFactory[Row] | None = None,
        cursor_factory: type[Cursor[Row]] | None = None,
        **kwargs: ConnParam,
    ) -> Self:
        """
        Connect to a database server and return a new
        `LogicalReplicationConnection` instance.
        """
        if "replication" in kwargs or "replication=" in conninfo:
            raise ValueError(
                "Unexpected connection parameter: replication."
                + "ReplicationConnections manage their own replication type."
            )
        kwargs["replication"] = cls._replication_connection_string
        return super().connect(
            conninfo,
            autocommit=autocommit,
            prepare_threshold=prepare_threshold,
            context=context,
            row_factory=row_factory,
            cursor_factory=cursor_factory,
            **kwargs,
        )


class LogicalReplicationConnection(BaseReplicationConnection[Row]):
    """
    Wrapper for a logical replication connection to the database
    (i.e. replication=database).
    """

    __module__ = "psycopg.replication"

    _replication_connection_string = "database"

    def __init__(
        self,
        pgconn: PGconn,
        row_factory: RowFactory[Row] = cast(RowFactory[Row], tuple_row),
    ):
        super().__init__(pgconn, row_factory)
        self.cursor_factory = LogicalReplicationCursor


class PhysicalReplicationConnection(BaseReplicationConnection[Row]):
    """
    Wrapper for a physical replication connection to the database
    (i.e. replication=true).
    """

    __module__ = "psycopg.replication"

    _replication_connection_string = "true"

    def __init__(
        self,
        pgconn: PGconn,
        row_factory: RowFactory[Row] = cast(RowFactory[Row], tuple_row),
    ):
        super().__init__(pgconn, row_factory)
        self.cursor_factory = PhysicalReplicationCursor
